# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 00:58
from __future__ import unicode_literals

import NEMO.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0008_version_1_16_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=NEMO.utilities.get_task_image_filename, verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Task')),
            ],
        ),
    ]
