# Generated by Django 2.2.10 on 2020-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0013_version_2_1_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
