# Generated by Django 2.2.13 on 2020-06-24 00:10

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0020_version_3_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaaccessrecord',
            name='area',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Area'),
        ),
        migrations.AlterField(
            model_name='door',
            name='area',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doors', to='NEMO.Area'),
        ),
        migrations.AlterField(
            model_name='physicalaccesslevel',
            name='area',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Area'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='area',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.Area'),
        ),
        migrations.AlterField(
            model_name='scheduledoutage',
            name='area',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.Area'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='_requires_area_access',
            field=mptt.fields.TreeForeignKey(blank=True, db_column='requires_area_access_id', help_text='Indicates that this tool is physically located in a billable area and requires an active area access record in order to be operated.', null=True, on_delete=django.db.models.deletion.PROTECT, to='NEMO.Area'),
        ),
    ]
