# Generated by Django 2.2.13 on 2020-06-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0020_version_3_0_0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_index=True, help_text='What is the name of this area? The name will be displayed on the tablet login and logout pages.', max_length=200),
        ),
    ]
