# Generated by Django 2.2.13 on 2020-06-30 19:38

import NEMO.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0020_version_3_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='abuse_email',
            field=NEMO.fields.MultiEmailField(blank=True, help_text='A email will be sent to this address when users overstay in the area or in children areas (logged in with expired reservation). A comma-separated list can be used.', max_length=2540, null=True),
        ),
    ]
