# Generated by Django 2.2.10 on 2020-06-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0020_version_3_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='parent_area',
            field=models.ForeignKey(blank=True, help_text='Select a parent area, (building, floor etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_children_set', to='NEMO.Area'),
        ),
        migrations.AddField(
            model_name='area',
            name='logout_grace_period',
            field=models.PositiveIntegerField(blank=True, help_text='Number of minutes users have to logout of this area after their reservation expired before being flagged and abuse email is sent.', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='requires_reservation',
            field=models.BooleanField(default=False, help_text='Check this box to require a reservation for this area before a user can login.'),
        ),
    ]
