# Generated by Django 2.2.13 on 2020-06-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0020_version_3_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='What is the name of this area? The name will be displayed on the tablet login and logout pages.', max_length=200),
        ),
        migrations.AlterField(
            model_name='areaaccessrecord',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['name'], name='NEMO_area_name_1e7670_idx'),
        ),
        migrations.AddIndex(
            model_name='areaaccessrecord',
            index=models.Index(fields=['end'], name='NEMO_areaac_end_fae061_idx'),
        ),
    ]
