# Generated by Django 2.2.13 on 2020-08-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0022_version_3_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='reminder_threshold_reached',
            field=models.BooleanField(default=False),
        ),
    ]
