# Generated by Django 2.2.13 on 2020-11-14 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0025_version_3_6_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the request was created.')),
                ('start', models.DateField(help_text='The start date the user is requesting a buddy.')),
                ('end', models.DateField(help_text='The end date the user is requesting a buddy.')),
                ('description', models.TextField(help_text='The description of the request.')),
                ('expired', models.BooleanField(default=False, help_text="Indicates the request has expired and won't be shown anymore.")),
                ('deleted', models.BooleanField(default=False, help_text="Indicates the request has been deleted and won't be shown anymore.")),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Area')),
                ('user', models.ForeignKey(help_text='The user who is submitting the request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='buddy_system_allowed',
            field=models.BooleanField(default=False, help_text='Check this box if the buddy system is allowed in this area.'),
        ),
        migrations.CreateModel(
            name='BuddyRequestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buddy_request', models.ForeignKey(help_text='The request that this message relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='NEMO.BuddyRequest')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
