# Generated by Django 2.2.13 on 2020-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0026_buddyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='display_new_buddy_request_notification',
            field=models.BooleanField(default=True, help_text='Whether or not to notify the user of new buddy requests (via unread badges)', verbose_name='new_buddy_request_notification'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='display_new_buddy_request_reply_notification',
            field=models.BooleanField(default=True, help_text='Whether or not to notify the user of replies on buddy request he commented on (via unread badges)', verbose_name='new_buddy_request_reply_notification'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_new_buddy_request_reply',
            field=models.BooleanField(default=True, help_text='Whether or not to email the user of replies on buddy request he commented on', verbose_name='email_new_buddy_request_reply'),
        ),
        migrations.AlterField(
            model_name='landingpagechoice',
            name='notifications',
            field=models.CharField(blank=True, choices=[('news', 'News creation and updates - notifies all users'), ('safetyissue', 'New safety issues - notifies staff only'), ('buddyrequest', 'New buddy request - notifies all users'), ('buddyrequestmessage', 'New buddy request reply - notifies request creator and users who have replied')], help_text="Displays a the number of new notifications for the user. For example, if the user has two unread news notifications then the number '2' would appear for the news icon on the landing page.", max_length=25, null=True),
        ),
    ]
