# Generated by Django 2.2.13 on 2021-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0026_version_3_7_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='to',
            field=models.TextField(),
        ),
    ]
