# Generated by Django 2.2.13 on 2021-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0026_version_3_7_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'General'), (1, 'System'), (2, 'Direct Contact'), (3, 'Broadcast Email'), (4, 'Timed Services'), (5, 'Feedback'), (6, 'Abuse'), (7, 'Safety'), (8, 'Tasks')], default=0)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=254)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('ok', models.BooleanField(default=True)),
                ('attachments', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
