# Generated by Django 2.2.13 on 2020-12-10 22:06

from django.db import migrations, models

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0027_version_3_8_0'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "3.9.0")

    operations = [
        migrations.AlterModelOptions(
            name='toolusagecounter',
            options={'ordering': ['tool__name']},
        ),
        migrations.AlterField(
            model_name='toolusagecounter',
            name='last_reset_value',
            field=models.FloatField(blank=True, help_text='The last value before the counter was reset', null=True),
        ),
        migrations.AlterField(
            model_name='toolusagecounter',
            name='value',
            field=models.FloatField(default=0, help_text='The current value of this counter'),
        ),
        migrations.RunPython(new_version_news),
    ]
