# Generated by Django 2.2.19 on 2021-03-22 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0028_version_3_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='principal_investigator',
            field=models.ForeignKey(blank=True, null=True, related_name="pi_project_set", on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
