# Generated by Django 2.2.13 on 2021-03-18 10:27

import NEMO.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0028_version_3_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooldocuments',
            name='name',
            field=models.CharField(blank=True, help_text='The optional name to display for this document', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tooldocuments',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tooldocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=NEMO.utilities.get_tool_document_filename, verbose_name='Document'),
        ),
    ]
