# Generated by Django 2.2.19 on 2021-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0029_project_principal_investigator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='principal_investigator',
        ),
        migrations.AddField(
            model_name='user',
            name='managed_projects',
            field=models.ManyToManyField(blank=True, help_text='Select the projects that this user is a PI for.', related_name='manager_set', to='NEMO.Project'),
        ),
    ]
