# Generated by Django 2.2.13 on 2021-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0030_version_3_9_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='_tool_calendar_color',
            field=models.CharField(db_column='tool_calendar_color', default='#33ad33', help_text='Color for tool reservations in calendar overviews', max_length=9),
        ),
        migrations.AddField(
            model_name='area',
            name='area_calendar_color',
            field=models.CharField(default='#88B7CD', help_text='Color for tool reservations in calendar overviews', max_length=9),
        ),

    ]
