# Generated by Django 2.2.20 on 2021-04-15 15:45

from django.db import migrations, models

import NEMO.fields
from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0030_version_3_9_2'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "3.10.0")

    operations = [
        migrations.AddField(
            model_name='project',
            name='only_allow_tools',
            field=models.ManyToManyField(blank=True, help_text='Selected tools will be the only ones allowed for this project.', to='NEMO.Tool'),
        ),
        migrations.AddField(
            model_name='toolusagecounter',
            name='warning_email',
            field=NEMO.fields.MultiEmailField(blank=True, help_text='The address to send the warning email to. A comma-separated list can be used.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='toolusagecounter',
            name='warning_threshold',
            field=models.FloatField(blank=True, help_text='When set in combination with the email address, a warning email will be sent when the counter reaches this value.', null=True),
        ),
        migrations.AddField(
            model_name='toolusagecounter',
            name='warning_threshold_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_consumable_withdrawals',
            field=models.BooleanField(default=True, help_text='Uncheck this box if consumable withdrawals are forbidden under this project'),
        ),
        migrations.RunPython(new_version_news),
    ]
