# Generated by Django 2.2.20 on 2021-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0030_version_3_9_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='only_allow_tools',
            field=models.ManyToManyField(blank=True, help_text='Selected tools will be the only ones allowed for this project.', to='NEMO.Tool'),
        ),
    ]
