# Generated by Django 2.2.20 on 2021-05-03 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0031_version_3_10_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='_superusers',
            field=models.ManyToManyField(blank=True, db_table='NEMO_tool_superusers', help_text='Superusers who can train users on this tool.', related_name='superuser_for_tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
