# Generated by Django 2.2.20 on 2021-04-20 17:39

import NEMO.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0031_version_3_10_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolusagecounter',
            name='warning_email',
            field=NEMO.fields.MultiEmailField(blank=True, help_text='The address to send the warning email to. A comma-separated list can be used.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_consumable_withdrawals',
            field=models.BooleanField(default=True, help_text='Uncheck this box if consumable withdrawals are forbidden under this project'),
        ),
    ]
