# Generated by Django 2.2.20 on 2021-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0031_version_3_10_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
