# Generated by Django 2.2.20 on 2021-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0032_version_3_11_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Check this box to keep this story at the top of the news feed'),
        ),
    ]
