# Generated by Django 2.2.20 on 2021-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0032_version_3_11_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationquestions',
            name='only_for_areas',
            field=models.ManyToManyField(blank=True, help_text='Select the areas these questions only apply to. Leave blank for all areas', to='NEMO.Area'),
        ),
        migrations.AddField(
            model_name='reservationquestions',
            name='only_for_tools',
            field=models.ManyToManyField(blank=True, help_text='Select the tools these questions only apply to. Leave blank for all tools', to='NEMO.Tool'),
        ),
    ]
