# Generated by Django 2.2.24 on 2022-01-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0035_version_3_14_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcharge',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
