# Generated by Django 2.2.24 on 2022-01-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0035_version_3_14_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcharge',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
