# Generated by Django 2.2.27 on 2022-03-01 20:26

from django.db import migrations, models

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0036_version_3_15_0'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "3.16.0")

    operations = [
        migrations.RunPython(new_version_news),
        migrations.AddField(
            model_name='configuration',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Only active configurations will show up for the selected tool'),
        ),
    ]
