# Generated by Django 3.2.12 on 2022-04-07 14:17

from django.db import migrations

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0038_version_4_0_0'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "4.1.0", "")

    operations = [
        migrations.RunPython(new_version_news),
    ]
