# Generated by Django 2.2.27 on 2022-03-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0038_version_4_0_0'),
    ]

    def add_web_relay_x_series(apps, schema_editor):
        InterlockCardCategory = apps.get_model("NEMO", "InterlockCardCategory")
        InterlockCardCategory.objects.create(name="ModbusTcp", key="modbus_tcp")

    operations = [
        migrations.RunPython(add_web_relay_x_series),
    ]
