# Generated by Django 3.2.12 on 2022-04-07 14:17

from django.db import migrations, models

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0038_version_4_0_0'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "4.1.0", "")

    operations = [
        migrations.RunPython(new_version_news),
        migrations.AddField(
            model_name='landingpagechoice',
            name='hide_from_staff',
            field=models.BooleanField(default=False, help_text='Hides this choice from staff and technicians. When checked, only normal users, facility managers and super-users can see the choice'),
        ),
        migrations.AlterField(
            model_name='landingpagechoice',
            name='hide_from_users',
            field=models.BooleanField(default=False, help_text='Hides this choice from normal users. When checked, only staff, technicians, facility managers and super-users can see the choice'),
        ),
    ]
