# Generated by Django 3.2.13 on 2022-05-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0039_version_4_1_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_alternate',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_access_request_updates',
            field=models.BooleanField(default=True, help_text='Send access request updates to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_buddy_request_replies',
            field=models.BooleanField(default=True, help_text='Send buddy request replies to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_reservation_emails',
            field=models.BooleanField(default=True, help_text='Send reservation emails to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_reservation_ending_reminders',
            field=models.BooleanField(default=True, help_text='Send reservation ending reminders to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_reservation_reminders',
            field=models.BooleanField(default=True, help_text='Send reservation reminders to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_task_updates',
            field=models.BooleanField(default=True, help_text='Send task updates to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_usage_reminders',
            field=models.BooleanField(default=True, help_text='Send usage reminders to my alternate email'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_broadcast_emails',
            field=models.BooleanField(default=True, help_text='Send broadcast emails to my alternate email'),
        ),
    ]
