# Generated by Django 3.2.14 on 2022-08-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0040_version_4_2_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffabsence',
            name='manager_note',
            field=models.TextField(blank=True, help_text='A note only visible to managers.', null=True),
        ),
        migrations.AlterField(
            model_name='staffabsence',
            name='description',
            field=models.TextField(blank=True, help_text='The absence description. This will be visible to anyone.', null=True),
        ),
    ]
