# Generated by Django 3.2.14 on 2022-09-06 17:54

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0041_version_4_2_1'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "4.3.0", "")

    def migrate_qualifications(apps, schema_editor):
        User = apps.get_model("NEMO", "User")
        Qualification = apps.get_model("NEMO", "Qualification")
        for user in User.objects.all():
            for tool in user.qualifications.all():
                Qualification.objects.create(tool=tool, user=user)

    operations = [
        migrations.RunPython(new_version_news),
        migrations.AddField(
            model_name='interlock',
            name='unit_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interlock',
            name='most_recent_reply_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_access_expiration_emails',
            field=models.BooleanField(default=True, help_text='Send access expiration emails to my alternate email'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_on', models.DateField(default=datetime.date.today)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(migrate_qualifications),
        migrations.AddField(
            model_name='user',
            name='tool_qualifications',
            field=models.ManyToManyField(blank=True, help_text='Select the tools that the user is qualified to use.', through='NEMO.Qualification', to='NEMO.Tool'),
        ),
        migrations.RemoveField(model_name='user', name='qualifications'),
        migrations.RenameField(
            model_name='user',
            old_name='tool_qualifications',
            new_name='qualifications',
        ),
        migrations.AlterModelTable(
            name='qualification',
            table='NEMO_user_qualifications',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_send_tool_qualification_expiration_emails',
            field=models.BooleanField(default=True, help_text='Send tool qualification expiration emails to my alternate email'),
        ),
    ]

