# Generated by Django 3.2.14 on 2022-09-06 17:54

from django.db import migrations, models

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0041_version_4_2_1'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "4.3.0", "")

    operations = [
        migrations.RunPython(new_version_news),
        migrations.AddField(
            model_name='interlock',
            name='unit_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]

