# Generated by Django 3.2.15 on 2022-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0042_version_4_3_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='contents',
            field=models.TextField(),
        ),
    ]
