# Generated by Django 3.2.16 on 2022-10-24 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0042_version_4_3_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringConsumableCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/identifier for this recurring charge.', max_length=200)),
                ('last_updated', models.DateTimeField(help_text='The time this charge was last modified.')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The number of consumables to charge.', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_charge', models.DateTimeField(blank=True, help_text='The date and time when the user was last charged.', null=True)),
                ('rec_start', models.DateField(verbose_name='start', blank=True, help_text='Start date of the recurring charge.', null=True)),
                ('rec_frequency', models.PositiveIntegerField(verbose_name='frequency', blank=True, choices=[(1, 'Day(s)'), (2, 'Week Day(s)'), (3, 'Weekend Day(s)'), (4, 'Week(s)'), (5, 'Month(s)'), (6, 'Year(s)')], help_text='The charge frequency.', null=True)),
                ('rec_interval', models.PositiveIntegerField(verbose_name='interval', default=1, help_text='Recurring interval, i.e. every 5 days.', validators=[django.core.validators.MinValueValidator(1)])),
                ('rec_until', models.DateField(verbose_name='until', blank=True, help_text='End date of the recurring charge.', null=True)),
                ('rec_count', models.PositiveIntegerField(verbose_name='count', blank=True, help_text='The number of recurrences to charge for.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.consumable')),
                ('customer', models.ForeignKey(blank=True, help_text='The user who will be charged.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charge_customer', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(help_text='The user who last modified this charge (and will be used as merchant on the charge).', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_charge_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The project to bill.', null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
