# Generated by Django 3.2.16 on 2023-01-25 14:49

from django.db import migrations

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0044_version_4_4_0'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "4.5.0", "")

    operations = [
        migrations.RunPython(new_version_news),
    ]

