# Generated by Django 3.2.16 on 2023-01-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0044_version_4_4_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discipline',
        ),
    ]
