# Generated by Django 3.2.18 on 2023-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0045_version_4_5_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffavailability',
            name='visible',
            field=models.BooleanField(default=True, help_text='Specifies whether this staff member should be displayed on the staff status page.'),
        ),
    ]
