# Generated by Django 3.2.18 on 2023-02-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('NEMO', '0045_version_4_5_0'),
    ]

    def migrate_request_messages(apps, schema_editor):
        RequestMessage = apps.get_model('NEMO', 'RequestMessage')
        for request_message in RequestMessage.objects.all():
            request_type = apps.get_model("contenttypes", "ContentType").objects.get_for_model(request_message.buddy_request)
            request_message.content_type = request_type
            request_message.object_id = request_message.buddy_request.id
            request_message.save(update_fields=["content_type", "object_id"])

    operations = [
        migrations.RenameModel(
            old_name='BuddyRequestMessage',
            new_name='RequestMessage',
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', null=True),
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(migrate_request_messages),
        migrations.AlterField(
            model_name='requestmessage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='requestmessage',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='requestmessage',
            name='buddy_request',
        ),
    ]
