# Generated by Django 3.2.18 on 2023-04-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0045_version_4_5_0'),
    ]

    def set_remote_work_flag(apps, schema_editor):
        UsageEvent = apps.get_model("NEMO", "UsageEvent")
        # go through all previous tool usage and set them to be remote work if operator is different from user
        for tool_usage in UsageEvent.objects.all():
            if tool_usage.user != tool_usage.operator:
                tool_usage.remote_work = True
                tool_usage.save(update_fields=["remote_work"])

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='remote_work',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_remote_work_flag),
    ]
