# Generated by Django 3.2.18 on 2023-03-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0045_version_4_5_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumablewithdraw',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
