# Generated by Django 3.2.18 on 2023-04-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0045_version_4_5_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='interlock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NEMO.interlock'),
        ),
    ]
