# Generated by Django 3.2.18 on 2023-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0046_alter_door_interlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolQualificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this tool group', max_length=200, unique=True)),
                ('tools', models.ManyToManyField(to='NEMO.Tool')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
