# Generated by Django 3.2.19 on 2023-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0046_version_4_6_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='_qualifications_never_expire',
            field=models.BooleanField(db_column='qualifications_never_expire', default=False, help_text='Check this box if qualifications for this tool should never expire (even if the tool qualification expiration feature is enabled).'),
        ),
    ]
