# Generated by Django 3.2.20 on 2023-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0047_userpreferences_tool_adjustment_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tool_task_notifications',
            field=models.ManyToManyField(blank=True, help_text='Tools to see maintenance records and receive task notifications for. If empty all notifications will be received.', related_name='_NEMO_userpreferences_tool_task_notifications_+', to='NEMO.Tool'),
        ),
    ]
