# Generated by Django 3.2.20 on 2023-07-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0048_userpreferences_tool_task_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablewithdraw',
            name='tool_usage',
            field=models.BooleanField(default=False, help_text='Whether this withdraw is from tool usage'),
        ),
    ]
