# Generated by Django 3.2.20 on 2023-09-14 01:54

from django.db import migrations, models

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0049_version_4_7_0'),
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "4.7.0", "The new version of the calendar allows users to view multiple tool feeds at once by checking the box next to each tool you would like to see.")

    operations = [
        migrations.RunPython(new_version_news),
        migrations.AddField(
            model_name='consumable',
            name='allow_self_checkout',
            field=models.BooleanField(default=True, help_text='Allow users to self checkout this consumable, only applicable when self checkout customization is enabled.'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the consumable.', null=True),
        ),
    ]
