# Generated by Django 3.2.22 on 2024-01-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NEMO", "0055_reservationconfigurationoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_pre_usage_questions",
            field=models.TextField(
                blank=True,
                db_column="pre_usage_questions",
                help_text="Before using a tool, questions can be asked. This field will only accept JSON format",
                null=True,
            ),
        ),
    ]
