# Generated by Django 3.2.23 on 2024-02-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0059_tool_pre_usage_questions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["first_name"],
                "permissions": (
                    ("trigger_timed_services", "Can trigger timed services"),
                    ("use_billing_api", "Can use billing API"),
                    ("kiosk", "Kiosk services"),
                    ("can_impersonate_users", "Can impersonate other users"),
                ),
            },
        ),
    ]
