# Generated by Django 3.2.23 on 2024-03-08 20:58

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0064_consumable_self_checkout_only_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="door",
            name="adjacent_area",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="When logging out, the user will be asked if they want to log in to this adjacent area",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjacent_doors",
                to="NEMO.area",
            ),
        ),
    ]
