# Generated by Django 3.2.23 on 2024-03-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0066_tool_ask_to_leave_area_when_done_using"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_staff_charges",
            field=models.BooleanField(
                default=True, help_text="Uncheck this box if staff charges are forbidden for this project"
            ),
        ),
    ]
