# Generated by Django 3.2.25 on 2024-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0072_documents_display_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="safetyitem",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="staffknowledgebaseitem",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="userknowledgebaseitem",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="safetyitem",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the items will be displayed within the same category. Lower values are displayed first.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffknowledgebaseitem",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the items will be displayed within the same category. Lower values are displayed first.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userknowledgebaseitem",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the items will be displayed within the same category. Lower values are displayed first.",
            ),
            preserve_default=False,
        ),
    ]
