# Generated by Django 3.2.25 on 2024-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0074_scheduled_outage_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmentrequest",
            name="applied",
            field=models.BooleanField(default=False, help_text="Indicates the adjustment has been applied"),
        ),
    ]
