# Generated by Django 3.2.25 on 2024-04-15 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0074_scheduled_outage_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmentrequest",
            name="applied",
            field=models.BooleanField(default=False, help_text="Indicates the adjustment has been applied"),
        ),
        migrations.AddField(
            model_name="adjustmentrequest",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustment_requests_applied",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
