# Generated by Django 3.2.25 on 2024-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0076_default_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="interlock",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
