# Generated by Django 4.2.11 on 2024-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0076_version_6_0_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="tool_task_notifications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tools to see maintenance records and receive task notifications for. If empty all notifications will be received.",
                related_name="+",
                to="NEMO.tool",
            ),
        ),
    ]
