# Generated by Django 3.2.25 on 2024-05-29 15:35
import hashlib

from django.db import connection, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0080_version_6_0_0"),
    ]

    operations = []
