# Generated by Django 4.2.11 on 2024-05-21 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0081_alter_userpreferences_tool_task_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolCredentials",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "authorized_staff",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Selected staff will be the only ones allowed to see these credentials. Leave blank for all staff.",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="NEMO.tool")),
            ],
            options={
                "verbose_name": "Tool credentials",
                "verbose_name_plural": "Tool credentials",
                "ordering": ["-tool__visible", "tool___category", "tool__name"],
            },
        ),
    ]
