# Generated by Django 4.2.11 on 2024-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0085_contactinformation_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmentrequest",
            name="new_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
