# Generated by Django 4.2.11 on 2024-06-11 02:00

from django.db import migrations

from NEMO.migrations_utils import news_for_version_forward, news_for_version_reverse


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0086_adjustmentrequest_new_quantity"),
    ]

    replaces = [
        ("NEMO", "0087_version_6_1_0"),  # Add this to indicate renaming
    ]

    operations = [
        migrations.RunPython(news_for_version_forward("7.0.0"), news_for_version_reverse("7.0.0")),
    ]
