# Generated by Django 4.2.11 on 2024-06-11 02:00

from django.db import migrations

from NEMO.migrations_utils import create_news_for_version


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0086_adjustmentrequest_new_quantity"),
    ]

    replaces = [
        ("NEMO", "0087_version_6_1_0"),  # Add this to indicate renaming
    ]

    def new_version_news(apps, schema_editor):
        create_news_for_version(apps, "7.0.0", "")

    operations = [
        migrations.RunPython(new_version_news),
    ]
