# Generated by Django 4.2.14 on 2024-07-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0087_version_6_1_0"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configurationoption",
            options={"ordering": ["configuration__display_order", "id"]},
        ),
    ]
