# Generated by Django 4.2.15 on 2024-09-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0089_door_farewell_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolusagecounter",
            name="counter_direction",
            field=models.IntegerField(choices=[(1, "Increment"), (-1, "Decrement")], default=1),
        ),
        migrations.AddField(
            model_name="toolusagecounter",
            name="default_value",
            field=models.FloatField(default=0, help_text="The default value to reset this counter to"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toolusagecounter",
            name="email_facility_managers_when_reset",
            field=models.BooleanField(
                default=True, help_text="Check this box to email facility managers when this counter is reset"
            ),
        ),
        migrations.AddField(
            model_name="toolusagecounter",
            name="qualified_users_can_reset",
            field=models.BooleanField(
                default=False, help_text="Check this box to allow qualified users to reset this counter"
            ),
        ),
        migrations.AddField(
            model_name="toolusagecounter",
            name="staff_members_can_reset",
            field=models.BooleanField(default=True, help_text="Check this box to allow staff to reset this counter"),
        ),
        migrations.AddField(
            model_name="toolusagecounter",
            name="superusers_can_reset",
            field=models.BooleanField(
                default=False, help_text="Check this box to allow tool superusers to reset this counter"
            ),
        ),
        migrations.AlterField(
            model_name="toolusagecounter",
            name="value",
            field=models.FloatField(help_text="The current value of this counter"),
        ),
    ]
