# Generated by Django 4.2.16 on 2024-11-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0093_trainingsession_usage_event_usageevent_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="interlockcard",
            name="extra_args",
            field=models.TextField(
                blank=True,
                help_text="Json formatted extra arguments to pass to the interlock card implementation.",
                null=True,
            ),
        ),
    ]
