# Generated by Django 4.2.15 on 2024-12-19 01:39

from django.db import migrations

import NEMO.fields


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0095_reservationquestions_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpagechoice",
            name="notifications",
            field=NEMO.fields.DynamicChoicesCharField(
                blank=True,
                help_text="Displays a the number of new notifications for the user. For example, if the user has two unread news notifications then the number '2' would appear for the news icon on the landing page.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=NEMO.fields.DynamicChoicesCharField(max_length=100),
        ),
    ]
