# Generated by Django 4.2.15 on 2025-01-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0096_alter_landingpagechoice_notifications_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The unique name for this item", max_length=255, unique=True)),
                (
                    "display_order",
                    models.IntegerField(
                        help_text="The display order is used to sort these items. The lowest value category is displayed first."
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="fund_types",
            field=models.ManyToManyField(blank=True, to="NEMO.fundtype"),
        ),
    ]
