# Generated by Django 4.2.17 on 2025-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0097_fundtype_project_fund_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="maximum_future_reservations",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_future_reservations",
                help_text="The maximum number of reservations a user may make in the future for this area.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_maximum_future_reservations",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_future_reservations",
                help_text="The maximum number of reservations a user may make in the future for this tool.",
                null=True,
            ),
        ),
    ]
