# Generated by Django 4.2.17 on 2025-02-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0098_tool_area_maximum_future_reservations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FundType",
            new_name="ProjectType",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="fund_types",
            new_name="project_types",
        ),
    ]
