# Generated by Django 4.2.19 on 2025-02-11 21:09

from django.db import migrations

import NEMO.fields


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0100_staff_assistance_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="category",
            field=NEMO.fields.DynamicChoicesIntegerField(default=0),
        ),
    ]
