# Generated by Django 4.2.19 on 2025-02-24 14:22

from django.db import migrations

from NEMO.migrations_utils import news_for_version_forward, news_for_version_reverse


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0101_alter_emaillog_category"),
    ]

    operations = [
        migrations.RunPython(news_for_version_forward("7.0.1"), news_for_version_reverse("7.0.1")),
    ]
