# Generated by Django 4.2.19 on 2025-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0102_version_7_0_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="safetyitemdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="staffknowledgebaseitemdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="tooldocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="userdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="userknowledgebaseitemdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
    ]
