# Generated by Django 4.2.19 on 2025-03-05 04:02

from django.db import migrations

from NEMO.migrations_utils import news_for_version_forward, news_for_version_reverse


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0103_alter_projectdocuments_display_order_and_more"),
    ]

    operations = [
        migrations.RunPython(news_for_version_forward("7.0.2"), news_for_version_reverse("7.0.2")),
    ]
