# Generated by Django 4.2.19 on 2025-03-12 02:45

from django.db import migrations

from NEMO.migrations_utils import news_for_version_forward, news_for_version_reverse


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0104_version_7_0_2"),
    ]

    operations = [
        migrations.RunPython(news_for_version_forward("7.1.0"), news_for_version_reverse("7.1.0")),
    ]
