# Generated by Django 4.2.19 on 2025-03-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0105_version_7_1_0"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolusagecounter",
            old_name="tool_usage_question",
            new_name="tool_post_usage_question",
        ),
        migrations.AlterField(
            model_name="toolusagecounter",
            name="tool_post_usage_question",
            field=models.CharField(
                blank=True,
                help_text="The name of the tool's post usage question which should be used to update this counter",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="toolusagecounter",
            name="tool_pre_usage_question",
            field=models.CharField(
                blank=True,
                help_text="The name of the tool's pre usage question which should be used to update this counter",
                max_length=255,
                null=True,
            ),
        ),
    ]
