# Generated by Django 4.2.20 on 2025-03-24 15:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0110_version_7_1_1"),
    ]

    operations = []
