# Generated by Django 4.2.19 on 2025-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0111_version_7_1_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
