# Generated by Django 4.2.20 on 2025-05-09 17:44

from django.db import migrations

from NEMO import migrations_utils


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0112_fix_project_name_uniqueness"),
    ]

    operations = [
        migrations.RunPython(
            migrations_utils.news_for_version_forward("7.2.0"), migrations_utils.news_for_version_reverse("7.2.0")
        ),
    ]
