# Generated by Django 4.2.20 on 2025-05-14 17:36

import NEMO.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0114_alter_temporaryphysicalaccess_options_tool__staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_properties",
            field=NEMO.fields.JsonField(blank=True, db_column="properties", null=True),
        ),
    ]
