# Generated by Django 4.2.20 on 2025-05-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0115_tool__properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
