# Generated by Django 4.2.20 on 2025-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0116_comment_pinned"),
    ]

    def set_usage_event_end_timestamp(apps, schema_editor):
        UsageEvent = apps.get_model("NEMO", "UsageEvent")
        for usage_event in UsageEvent.objects.all():
            usage_event.end_timestamp = 0 if usage_event.end is None else int(usage_event.end.timestamp() * 1000)
            usage_event.save()

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="end_timestamp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_usage_event_end_timestamp, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="usageevent",
            constraint=models.UniqueConstraint(fields=("tool", "end_timestamp"), name="unique_tool_end_timestamp"),
        ),
    ]
