# Generated by Django 4.2.20 on 2025-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0117_usageevent_end_timestamp_and_more"),
    ]

    def set_area_access_end_timestamp(apps, schema_editor):
        AreaAccessRecord = apps.get_model("NEMO", "AreaAccessRecord")
        for area_access in AreaAccessRecord.objects.all():
            area_access.end_timestamp = 0 if area_access.end is None else int(area_access.end.timestamp() * 1000)
            area_access.save()

    operations = [
        migrations.AddField(
            model_name="areaaccessrecord",
            name="end_timestamp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_area_access_end_timestamp, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="areaaccessrecord",
            constraint=models.UniqueConstraint(
                fields=("customer", "area", "end_timestamp"), name="unique_area_user_end_timestamp"
            ),
        ),
    ]
