# Generated by Django 4.2.20 on 2025-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0118_areaaccessrecord_end_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatus",
            name="notify_tool_staff",
            field=models.BooleanField(
                default=False,
                help_text="Notify the users who are staff on this tool when a task transitions to this status",
            ),
        ),
    ]
