# Generated by Django 4.2.23 on 2025-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0119_taskstatus_notify_tool_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={
                "ordering": ["user"],
                "verbose_name": "User preferences",
                "verbose_name_plural": "User preferences",
            },
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="attach_cancelled_reservation",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to send a calendar invitation when cancelling a reservation",
                verbose_name="Cancelled reservation invite",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="attach_created_reservation",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to send a calendar invitation when creating a new reservation",
                verbose_name="Created reservation invite",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="display_new_buddy_request_notification",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not to notify the user of new buddy requests (via unread badges)",
                verbose_name="New buddy request notification",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="email_new_adjustment_request_reply",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not to email the user of replies on adjustment request he commented on",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="email_new_buddy_request_reply",
            field=models.BooleanField(
                default=True, help_text="Whether or not to email the user of replies on buddy request he commented on"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="staff_status_view",
            field=models.CharField(
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                default="day",
                help_text="Preferred view for staff status page",
                max_length=100,
            ),
        ),
    ]
