# Generated by Django 4.2.20 on 2025-05-09 17:44

from django.db import migrations

from NEMO import migrations_utils


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0120_alter_userpreferences_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrations_utils.news_for_version_forward("7.3.0"), migrations_utils.news_for_version_reverse("7.3.0")
        ),
    ]
