# Generated by Django 4.2.20 on 2025-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0121_version_7_3_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_accounts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the accounts that this user is a manager for.",
                related_name="manager_set",
                to="NEMO.account",
            ),
        ),
    ]
