# Generated by Django 4.2.20 on 2025-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0121_user_managed_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
