# Generated by Django 4.2.20 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0122_account_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="login_redirect_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
