# Generated by Django 4.2.24 on 2025-09-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0125_alter_reservationquestions_name_toolusagequestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="abuse_weight",
            field=models.IntegerField(
                default=1,
                verbose_name="Reservation abuse weight",
                help_text="The weight to give this area in the reservation abuse calculations",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_abuse_weight",
            field=models.IntegerField(
                db_column="abuse_weight",
                default=1,
                verbose_name="Reservation abuse weight",
                help_text="The weight to give this tool in the reservation abuse calculations",
            ),
        ),
    ]
