# Generated by Django 4.2.24 on 2025-09-21 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0126_area_abuse_weight_tool__abuse_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCalendarToolList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The name of the list of calendar tools", max_length=255, unique=True),
                ),
                ("tools", models.ManyToManyField(help_text="The comma-separated list of tool ids", to="NEMO.tool")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this list is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "name"],
            },
        ),
    ]
