# Generated by Django 4.2.24 on 2025-09-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0127_usercalendartoollist"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmentrequest",
            name="new_project",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="NEMO.project"
            ),
        ),
    ]
