# Generated by Django 4.2.24 on 2025-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0129_adjustmentrequest_original_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
