# Generated by Django 4.2.25 on 2025-11-04 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0130_reservation_note_alter_tool__staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the users that this user is managing.",
                related_name="supervisors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
