# Generated by Django 4.2.25 on 2025-11-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("NEMO", "0132_toolusagequestions_users_and_tools_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolusagequestions",
            name="only_for_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the user groups these questions only apply to. Leave blank for all users",
                to="auth.group",
            ),
        ),
    ]
