# Generated by Django 4.2.25 on 2025-11-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0133_toolusagequestions_only_for_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
