# Generated by Django 4.2.26 on 2025-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0134_usageevent_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_problem_shutdown_enabled",
            field=models.BooleanField(
                db_column="problem_shutdown_enabled",
                default=True,
                help_text="Whether or not users can shut down the tool when reporting a problem.",
            ),
        ),
    ]
