# Generated by Django 4.2.25 on 2025-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0135_tool__problem_shutdown_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_requires_area_occupancy_minimum",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="requires_area_occupancy_minimum",
                help_text="Enter the minimum number of total users needed to be present in the required area to enable this tool",
                null=True,
            ),
        ),
    ]
