# Generated by Django 4.2.27 on 2026-01-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0136_tool__requires_area_occupancy_minimum"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["tree_id", "lft"], name="NEMO_area_tree_id_lft_idx"),
        ),
    ]
