# Generated by Django 4.2.27 on 2026-01-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0137_area_nemo_area_tree_id_lft_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="late_cancellation_reservation_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="late_cancellation_reservation_threshold",
                help_text='The amount of time (in minutes) before its start time that a area reservation may be canceled before it is automatically marked as "missed" and hidden from the calendar. Usage can be from any user, regardless of who the reservation was originally created for. The cancellation process is triggered by a timed job on the web server.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_late_cancellation_reservation_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="late_cancellation_reservation_threshold",
                help_text='The amount of time (in minutes) before its start time that a tool reservation may be canceled before it is automatically marked as "missed" and hidden from the calendar.',
                null=True,
            ),
        ),
    ]
