# Generated by Django 4.2.27 on 2026-01-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0138_area_late_cancellation_reservation_threshold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnplannedOutage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("tool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="NEMO.tool")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
