# Generated by Django 4.2.27 on 2026-01-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0139_unplannedoutage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["first_name"],
                "permissions": (
                    ("trigger_timed_services", "Can trigger timed services"),
                    ("use_billing_api", "Can use billing API"),
                    ("use_project_billing", "Can use project billing"),
                    ("kiosk", "Kiosk services"),
                    ("can_impersonate_users", "Can impersonate other users"),
                ),
            },
        ),
    ]
