# Generated by Django 4.2.27 on 2026-01-26 20:42

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import NEMO.fields


def migrate_tool_qualification_expiration_forward(apps, schema_editor):
    Tool = apps.get_model("NEMO", "Tool")
    Customization = apps.get_model("NEMO", "Customization")
    tool_qualification_reminder_days = Customization.objects.filter(name="tool_qualification_reminder_days").first()
    tool_qualification_expiration_days = Customization.objects.filter(name="tool_qualification_expiration_days").first()
    tool_qualification_expiration_never_used_days = Customization.objects.filter(
        name="tool_qualification_expiration_never_used_days"
    ).first()
    tool_qualification_notification = Customization.objects.filter(name="tool_qualification_cc").first()
    for tool in Tool.objects.filter(_qualifications_never_expire=False, parent_tool__isnull=True):
        if tool_qualification_expiration_days or tool_qualification_expiration_never_used_days:
            if tool_qualification_reminder_days and tool_qualification_reminder_days.value:
                tool._qualification_reminder_days = tool_qualification_reminder_days.value
            if tool_qualification_expiration_days and tool_qualification_expiration_days.value:
                tool._qualification_expiration_days = tool_qualification_expiration_days.value
            if tool_qualification_expiration_never_used_days and tool_qualification_expiration_never_used_days.value:
                tool._qualification_expiration_never_used_days = tool_qualification_expiration_never_used_days.value
            if tool_qualification_notification and tool_qualification_notification.value:
                tool._qualification_notification_email = tool_qualification_notification.value
            tool.save()
    if tool_qualification_reminder_days:
        tool_qualification_reminder_days.delete()
    if tool_qualification_expiration_days:
        tool_qualification_expiration_days.delete()
    if tool_qualification_expiration_never_used_days:
        tool_qualification_expiration_never_used_days.delete()
    if tool_qualification_notification:
        tool_qualification_notification.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0140_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_qualification_expiration_days",
            field=models.PositiveIntegerField(
                db_column="qualification_expiration_days",
                blank=True,
                help_text="The number of days from the user’s last tool use until the qualification expires.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_qualification_expiration_never_used_days",
            field=models.PositiveIntegerField(
                db_column="qualification_expiration_never_used_days",
                blank=True,
                help_text="Number of days from the user's first qualification until the qualification expires (if the user never used the tool).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_qualification_notification_email",
            field=NEMO.fields.MultiEmailField(
                db_column="qualification_notification_email",
                blank=True,
                help_text="The email addresses to cc on tool qualification expiration and on reminders. Separate multiple emails with commas.",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_qualification_reminder_days",
            field=models.CharField(
                db_column="qualification_reminder_days",
                blank=True,
                help_text="The (optional) number of days to send a reminder prior to the user's tool qualification expiration (below). A comma-separated list can be used for multiple reminders. This applies to both expiration cases.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.RunPython(migrate_tool_qualification_expiration_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tool",
            name="_qualifications_never_expire",
        ),
    ]
