# Generated by Django 4.2.27 on 2026-01-26 20:42

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from NEMO import fields


def migrate_tool_qualification_expiration_forward(apps, schema_editor):
    ToolQualificationExpiration = apps.get_model("NEMO", "ToolQualificationExpiration")
    Tool = apps.get_model("NEMO", "Tool")
    Customization = apps.get_model("NEMO", "Customization")
    tool_qualification_reminder_days = Customization.objects.filter(name="tool_qualification_reminder_days").first()
    tool_qualification_expiration_days = Customization.objects.filter(name="tool_qualification_expiration_days").first()
    tool_qualification_expiration_never_used_days = Customization.objects.filter(
        name="tool_qualification_expiration_never_used_days"
    ).first()
    tool_qualification_notification = Customization.objects.filter(name="tool_qualification_cc").first()
    for tool in Tool.objects.filter(_qualifications_never_expire=False, parent_tool__isnull=True):
        if tool_qualification_expiration_days or tool_qualification_expiration_never_used_days:
            tool_exp = ToolQualificationExpiration(tool=tool)
            if tool_qualification_reminder_days and tool_qualification_reminder_days.value:
                tool_exp.reminder_days = tool_qualification_reminder_days.value
            if tool_qualification_expiration_days and tool_qualification_expiration_days.value:
                tool_exp.expiration_days = tool_qualification_expiration_days.value
            if tool_qualification_expiration_never_used_days and tool_qualification_expiration_never_used_days.value:
                tool_exp.expiration_never_used_days = tool_qualification_expiration_never_used_days.value
            if tool_qualification_notification and tool_qualification_notification.value:
                tool_exp.notification_email = tool_qualification_notification.value
            tool_exp.save()
    if tool_qualification_reminder_days:
        tool_qualification_reminder_days.delete()
    if tool_qualification_expiration_days:
        tool_qualification_expiration_days.delete()
    if tool_qualification_expiration_never_used_days:
        tool_qualification_expiration_never_used_days.delete()
    if tool_qualification_notification:
        tool_qualification_notification.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0140_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolQualificationExpiration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reminder_days",
                    models.CharField(
                        blank=True,
                        help_text="The (optional) number of days to send a reminder prior to the user's tool qualification expiration (below). A comma-separated list can be used for multiple reminders. This applies to both expiration cases.",
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d+(?:,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                    ),
                ),
                (
                    "expiration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The number of days from the user’s last tool use until the qualification expires.",
                        null=True,
                    ),
                ),
                (
                    "expiration_never_used_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days from the user's first qualification until the qualification expires.",
                        null=True,
                    ),
                ),
                (
                    "notification_email",
                    fields.MultiEmailField(
                        blank=True,
                        null=True,
                        help_text="The email addresses to cc on tool qualification expiration and on reminders. Separate multiple emails with commas.",
                    ),
                ),
                ("tool", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="NEMO.tool")),
            ],
            options={
                "abstract": False,
                "ordering": ["tool_id"],
            },
        ),
        migrations.RunPython(migrate_tool_qualification_expiration_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tool",
            name="_qualifications_never_expire",
        ),
    ]
