# Generated by Django 4.2.27 on 2026-02-05 16:02

import NEMO.fields
import NEMO.utilities
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0141_toolqualificationexpiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="_adjustment_request_reviewers",
            field=models.ManyToManyField(
                blank=True,
                db_table="NEMO_tool_adjustment_request_reviewers",
                help_text="Users who can approve/deny adjustment requests for this tool. Defaults to facility managers if left blank.",
                related_name="adjustment_request_reviewer_on_tools",
                to=settings.AUTH_USER_MODEL,
                verbose_name="adjustment_request_reviewers",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_ask_to_leave_area_when_done_using",
            field=models.BooleanField(
                db_column="ask_to_leave_area_when_done_using",
                default=False,
                help_text="Check this box to ask the user if they want to log out of the area when they are done using the tool.",
                verbose_name="ask_to_leave_area_when_done_using",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_backup_owners",
            field=models.ManyToManyField(
                blank=True,
                db_table="NEMO_tool_backup_owners",
                help_text="Alternate staff members who are responsible for administration of this tool when the primary owner is unavailable.",
                related_name="backup_for_tools",
                to=settings.AUTH_USER_MODEL,
                verbose_name="backup_owners",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_category",
            field=models.CharField(
                blank=True,
                db_column="category",
                help_text='Create sub-categories using slashes. For example "Category 1/Sub-category 1".',
                max_length=1024,
                null=True,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_description",
            field=models.TextField(
                blank=True,
                db_column="description",
                help_text="HTML syntax could be used",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_grant_badge_reader_access_upon_qualification",
            field=models.CharField(
                blank=True,
                db_column="grant_badge_reader_access_upon_qualification",
                help_text="Badge reader access is granted to the user upon qualification for this tool.",
                max_length=100,
                null=True,
                verbose_name="grant_badge_reader_access_upon_qualification",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_grant_physical_access_level_upon_qualification",
            field=models.ForeignKey(
                blank=True,
                db_column="grant_physical_access_level_upon_qualification_id",
                help_text="The designated physical access level is granted to the user upon qualification for this tool.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="NEMO.physicalaccesslevel",
                verbose_name="grant_physical_access_level_upon_qualification",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_image",
            field=models.ImageField(
                blank=True,
                db_column="image",
                help_text="An image that represent the tool. Maximum width and height are 500px",
                upload_to=NEMO.utilities.get_tool_image_filename,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_interlock",
            field=models.OneToOneField(
                blank=True,
                db_column="interlock_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="NEMO.interlock",
                verbose_name="interlock",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_late_cancellation_reservation_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="late_cancellation_reservation_threshold",
                help_text='The amount of time (in minutes) before its start time that a tool reservation may be canceled before it is automatically marked as "missed" and hidden from the calendar.',
                null=True,
                verbose_name="late_cancellation_reservation_threshold",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_location",
            field=models.CharField(
                blank=True, db_column="location", max_length=100, null=True, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_max_delayed_logoff",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="max_delayed_logoff",
                help_text='[Optional] Maximum delay in minutes that users may enter upon logging off before another user may use the tool. Some tools require "spin-down" or cleaning time after use. Leave blank to disable.',
                null=True,
                verbose_name="max_delayed_logoff",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_maximum_future_reservation_time",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_future_reservation_time",
                help_text="The maximum amount of time (in minutes) that a user may reserve from the current time onwards.",
                null=True,
                verbose_name="maximum_future_reservation_time",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_maximum_future_reservations",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_future_reservations",
                help_text="The maximum number of reservations a user may make in the future for this tool.",
                null=True,
                verbose_name="maximum_future_reservations",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_maximum_reservations_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_reservations_per_day",
                help_text="The maximum number of reservations a user may make per day for this tool.",
                null=True,
                verbose_name="maximum_reservations_per_day",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_maximum_usage_block_time",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="maximum_usage_block_time",
                help_text="The maximum amount of time (in minutes) that a user may reserve this tool for a single reservation. Leave this field blank to indicate that no maximum usage block time exists for this tool.",
                null=True,
                verbose_name="maximum_usage_block_time",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_minimum_time_between_reservations",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="minimum_time_between_reservations",
                help_text="The minimum amount of time (in minutes) that the same user must have between any two reservations for this tool.",
                null=True,
                verbose_name="minimum_time_between_reservations",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_minimum_usage_block_time",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="minimum_usage_block_time",
                help_text="The minimum amount of time (in minutes) that a user must reserve this tool for a single reservation. Leave this field blank to indicate that no minimum usage block time exists for this tool.",
                null=True,
                verbose_name="minimum_usage_block_time",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_missed_reservation_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="missed_reservation_threshold",
                help_text='The amount of time (in minutes) that a tool reservation may go unused before it is automatically marked as "missed" and hidden from the calendar. Usage can be from any user, regardless of who the reservation was originally created for. The cancellation process is triggered by a timed job on the web server.',
                null=True,
                verbose_name="missed_reservation_threshold",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_notification_email_address",
            field=models.EmailField(
                blank=True,
                db_column="notification_email_address",
                help_text="Messages that relate to this tool (such as comments, problems, and shutdowns) will be forwarded to this email address. This can be a normal email address or a mailing list address.",
                max_length=254,
                null=True,
                verbose_name="notification_email_address",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_operation_mode",
            field=models.IntegerField(
                choices=[(0, "Regular"), (1, "Wait List"), (2, "Hybrid")],
                default=0,
                help_text="The operation mode of the tool, which determines if reservations and wait list are allowed.",
                verbose_name="operation_mode",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_operational",
            field=models.BooleanField(
                db_column="operational",
                default=False,
                help_text="Marking the tool non-operational will prevent users from using the tool.",
                verbose_name="operational",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_phone_number",
            field=models.CharField(
                blank=True, db_column="phone_number", max_length=100, null=True, verbose_name="phone_number"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_policy_off_between_times",
            field=models.BooleanField(
                db_column="policy_off_between_times",
                default=False,
                help_text="Check this box to disable policy rules every day between the given times",
                verbose_name="policy_off_between_times",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_policy_off_end_time",
            field=models.TimeField(
                blank=True,
                db_column="policy_off_end_time",
                help_text="The end time when policy rules should NOT be enforced",
                null=True,
                verbose_name="policy_off_end_time",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_policy_off_start_time",
            field=models.TimeField(
                blank=True,
                db_column="policy_off_start_time",
                help_text="The start time when policy rules should NOT be enforced",
                null=True,
                verbose_name="policy_off_start_time",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_policy_off_weekend",
            field=models.BooleanField(
                db_column="policy_off_weekend",
                default=False,
                help_text="Whether or not policy rules should be enforced on weekends",
                verbose_name="policy_off_weekend",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_primary_owner",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_owner_id",
                help_text="The staff member who is responsible for administration of this tool.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_tool_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="primary_owner",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_problem_shutdown_enabled",
            field=models.BooleanField(
                db_column="problem_shutdown_enabled",
                default=True,
                help_text="Whether or not users can shut down the tool when reporting a problem.",
                verbose_name="problem_shutdown_enabled",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_properties",
            field=models.JSONField(blank=True, db_column="properties", null=True, verbose_name="properties"),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_qualification_expiration_days",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="qualification_expiration_days",
                help_text="The number of days from the user’s last tool use until the qualification expires.",
                null=True,
                verbose_name="qualification_expiration_days",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_qualification_expiration_never_used_days",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="qualification_expiration_never_used_days",
                help_text="Number of days from the user's first qualification until the qualification expires (if the user never used the tool).",
                null=True,
                verbose_name="qualification_expiration_never_used_days",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_qualification_notification_email",
            field=NEMO.fields.MultiEmailField(
                blank=True,
                db_column="qualification_notification_email",
                help_text="The email addresses to cc on tool qualification expiration and on reminders. Separate multiple emails with commas.",
                max_length=2000,
                null=True,
                verbose_name="qualification_notification_email",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_qualification_reminder_days",
            field=models.CharField(
                blank=True,
                db_column="qualification_reminder_days",
                help_text="The (optional) number of days to send a reminder prior to the user's tool qualification expiration (below). A comma-separated list can be used for multiple reminders. This applies to both expiration cases.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
                verbose_name="qualification_reminder_days",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_requires_area_access",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                db_column="requires_area_access_id",
                help_text="Indicates that this tool is physically located in a billable area and requires an active area access record in order to be operated.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="NEMO.area",
                verbose_name="Requires_area_access_id",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_requires_area_occupancy_minimum",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="requires_area_occupancy_minimum",
                help_text="Enter the minimum number of total users needed to be present in the required area to enable this tool",
                null=True,
                verbose_name="requires_area_occupancy_minimum",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_reservation_horizon",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="reservation_horizon",
                default=14,
                help_text="Users may create reservations this many days in advance. Leave this field blank to indicate that no reservation horizon exists for this tool.",
                null=True,
                verbose_name="reservation_horizon",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_serial",
            field=models.CharField(
                blank=True,
                db_column="serial",
                help_text="Serial Number",
                max_length=100,
                null=True,
                verbose_name="serial",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_superusers",
            field=models.ManyToManyField(
                blank=True,
                db_table="NEMO_tool_superusers",
                help_text="Superusers who can train users on this tool.",
                related_name="superuser_for_tools",
                to=settings.AUTH_USER_MODEL,
                verbose_name="superusers",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_tool_calendar_color",
            field=models.CharField(
                db_column="tool_calendar_color",
                default="#33ad33",
                help_text="Color for tool reservations in calendar overviews",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
                verbose_name="tool_calendar_color",
            ),
        ),
    ]
