# Generated by Django 4.2.27 on 2026-02-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0142_alter_tool__adjustment_request_reviewers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="staff_charge",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="NEMO.staffcharge"
            ),
        ),
    ]
