# Generated by Django 4.2.27 on 2026-03-28 18:43

from django.db import migrations

from NEMO import migrations_utils


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0144_alter_tool__adjustment_request_reviewers_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrations_utils.news_for_version_forward("7.4.0"), migrations_utils.news_for_version_reverse("7.4.0")
        ),
    ]
