# Generated by Django 5.2.13 on 2026-04-21 13:26

from django.db import migrations

from NEMO import migrations_utils


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0146_simplify_remote_work_on_behalf_of_user"),
    ]

    operations = [
        migrations.RunPython(
            migrations_utils.news_for_version_forward("8.0.0"), migrations_utils.news_for_version_reverse("8.0.0")
        ),
    ]
