# Generated by Django 5.2.13 on 2026-05-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0147_version_8_0_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="unplannedoutage",
            name="resource",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="NEMO.resource"
            ),
        ),
        migrations.AlterField(
            model_name="unplannedoutage",
            name="tool",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="NEMO.tool"),
        ),
    ]
