# Generated by Django 5.2.14 on 2026-05-20 19:39
from NEMO import migrations_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0148_unplannedoutage_resource_alter_unplannedoutage_tool"),
    ]

    operations = [
        migrations.RunPython(
            migrations_utils.news_for_version_forward("8.1.0"), migrations_utils.news_for_version_reverse("8.1.0")
        ),
    ]
