# Generated by Django 5.2.13 on 2026-05-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0149_version_8_1_0"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreFacility",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The name of this core facility.", max_length=255, unique=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="An external ID to associate with this core facility.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Core facilities",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="area",
            name="core_facility",
            field=models.ForeignKey(
                blank=True,
                help_text="The core facility this area belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to="NEMO.corefacility",
            ),
        ),
        migrations.AddField(
            model_name="consumable",
            name="core_facility",
            field=models.ForeignKey(
                blank=True,
                help_text="The core facility this consumable belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumables",
                to="NEMO.corefacility",
            ),
        ),
        migrations.AddField(
            model_name="staffcharge",
            name="core_facility",
            field=models.ForeignKey(
                blank=True,
                help_text="The core facility this staff charge belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_charges",
                to="NEMO.corefacility",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_core_facility",
            field=models.ForeignKey(
                blank=True,
                db_column="core_facility_id",
                help_text="The core facility this tool belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tools",
                to="NEMO.corefacility",
                verbose_name="core facility",
            ),
        ),
    ]
