# Generated by Django 5.2.17 on 2026-08-24 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0150_corefacility_area_core_facility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiphistory",
            name="authorizer",
            field=models.ForeignKey(
                blank=True,
                help_text="The staff member who changed the membership status of the account, project, or user in question.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
