# Generated by Django 5.2.17 on 2026-09-07 22:31

import django.core.validators
import re
from django.db import migrations, models
from django.db.models import F


def copy_custom_calendar_colors_to_reservation(apps, schema_editor):
    # Copy tool/area color if it was customized to the usage/access color for consistency with previous behavior
    Tool = apps.get_model("NEMO", "Tool")
    Area = apps.get_model("NEMO", "Area")
    Tool.objects.exclude(_tool_calendar_color__iexact="#33ad33").update(
        _tool_reservation_calendar_color=F("_tool_calendar_color")
    )
    Area.objects.exclude(area_calendar_color__iexact="#88b7cd").update(
        area_reservation_calendar_color=F("area_calendar_color")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0151_alter_membershiphistory_authorizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="area_reservation_calendar_color",
            field=models.CharField(
                default="#88b7cd",
                help_text="Color for area reservations in calendar overviews",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="_tool_reservation_calendar_color",
            field=models.CharField(
                db_column="tool_reservation_calendar_color",
                default="#88b7cd",
                help_text="Color for tool reservations in calendar overviews",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
                verbose_name="tool reservation calendar color",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="area_calendar_color",
            field=models.CharField(
                default="#88b7cd",
                help_text="Color for area access in calendar overviews",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_tool_calendar_color",
            field=models.CharField(
                db_column="tool_calendar_color",
                default="#33ad33",
                help_text="Color for tool usage in calendar overviews",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
                verbose_name="tool usage calendar color",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_calendar_color",
            field=models.CharField(
                default="#88b7cd",
                help_text="Color for project in calendar overviews (takes precedence over tool or area colors)",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.RunPython(copy_custom_calendar_colors_to_reservation, migrations.RunPython.noop),
    ]
