# Generated by Django 5.2.17 on 2026-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0151_alter_membershiphistory_authorizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Secret token used to authenticate this user's calendar subscription feed (webcal/ICS).",
                null=True,
                unique=True,
            ),
        ),
    ]
