# Generated by Django 5.2.17 on 2026-09-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0152_user_calendar_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="A short summary of the problem. When set, this is shown instead of the full description in lists and status displays, and the full description is only shown once the task is expanded.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
