# Generated by Django 5.2.17 on 2026-09-13 16:29

import django.db.models.deletion
from django.db import migrations, models


def set_tool_qualification_group_charge_tool(apps, schema_editor):
    ToolQualificationGroup = apps.get_model("NEMO", "ToolQualificationGroup")
    for group in ToolQualificationGroup.objects.all():
        group.training_charge_tool = group.tools.first()
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0153_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolqualificationgroup",
            name="training_charge_tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="toolqualificationgroup_charge_set",
                null=True,
                blank=True,
                to="NEMO.tool",
            ),
        ),
        migrations.RunPython(set_tool_qualification_group_charge_tool, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="toolqualificationgroup",
            name="training_charge_tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="toolqualificationgroup_charge_set",
                to="NEMO.tool",
            ),
        ),
    ]
