# Generated by Django 5.2.17 on 2026-09-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0153_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="staff_only_progress_description",
            field=models.TextField(
                blank=True,
                help_text="Additional progress notes visible only to staff (never included in task update emails.)",
                null=True,
            ),
        ),
    ]
