# Generated by Django 5.2.17 on 2026-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0154_toolqualificationgroup_training_charge_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "permissions": [
                    ("block_create_reservations", "Cannot create reservations"),
                    ("block_create_outages", "Cannot create outages"),
                    ("block_enable_tools", "Cannot enable tools"),
                    ("block_enter_any_areas", "Cannot enter any areas"),
                    ("block_bill_projects", "Cannot bill projects"),
                    ("block_qualify_on_tools", "Cannot qualify user on tools"),
                    ("block_add_physical_access_levels", "Cannot add physical access levels to user"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
