# Generated by Django 5.2.17 on 2026-09-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0154_task_staff_only_progress_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffabsencetype",
            name="remote_work",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that staff members with this absence type are working remotely (e.g. from home) rather than fully absent. This is shown differently than a full absence on the staff status page.",
            ),
        ),
    ]
