# Generated by Django 5.2.17 on 2026-09-30 20:10
from NEMO import migrations_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0155_policy_alter_activityhistory_options"),
    ]

    operations = [
        migrations.RunPython(
            migrations_utils.news_for_version_forward("8.2.0"), migrations_utils.news_for_version_reverse("8.2.0")
        ),
    ]
