# Generated by Django 5.2.17 on 2026-09-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0157_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolqualificationgroup",
            name="tool_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other tool qualification groups to include in this group. Nested groups are resolved recursively.",
                related_name="parent_tool_groups",
                to="NEMO.toolqualificationgroup",
            ),
        ),
        migrations.AlterField(
            model_name="toolqualificationgroup",
            name="tools",
            field=models.ManyToManyField(blank=True, to="NEMO.tool"),
        ),
    ]
