# Generated by Django 3.2.19 on 2023-05-30 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the service contract', max_length=255)),
                ('submitted_date', models.DateField(blank=True, help_text='The date this service contract was submitted', null=True)),
                ('award_date', models.DateField(blank=True, help_text='The date this service contract was awarded', null=True)),
                ('contract_number', models.CharField(blank=True, help_text='The service contract number', max_length=255, null=True)),
                ('requisition_number', models.CharField(blank=True, help_text='The requisition number for this service contract', max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='The cost of this service contract', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('procurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contracts.procurement')),
                ('current_year', models.PositiveIntegerField(default=1, help_text='The total number of years of this service contract', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_years', models.PositiveIntegerField(default=1, help_text='The current year for this service contract', validators=[django.core.validators.MinValueValidator(1)])),
                ('renewal_date', models.DateField(blank=True, help_text='The date this service contract is set for renewal', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('contracts.procurement',),
        ),
        migrations.CreateModel(
            name='ContractorAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the contractor', max_length=255)),
                ('start', models.DateField(blank=True, help_text='Start date of the contractor agreement', null=True)),
                ('end', models.DateField(blank=True, help_text='The end date of this contractor agreement', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, help_text='The contract this contractor is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.procurement')),
            ],
            options={
                'ordering': ['contract', '-start'],
            },
        ),
    ]
