# Generated by Django 3.2.19 on 2023-06-02 23:13

import NEMO.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=NEMO.utilities.document_filename_upload, verbose_name='Document')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('name', models.CharField(blank=True, help_text='The optional name to display for this document', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.procurement')),
            ],
            options={
                'verbose_name_plural': 'Procurement documents',
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractorAgreementDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=NEMO.utilities.document_filename_upload, verbose_name='Document')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('name', models.CharField(blank=True, help_text='The optional name to display for this document', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contractor_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractoragreement')),
            ],
            options={
                'verbose_name_plural': 'Contractor agreement documents',
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
    ]
