# Generated by Django 3.2.25 on 2024-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_increase_document_path_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractoragreementdocuments",
            options={
                "ordering": ["display_order", "-uploaded_at"],
                "verbose_name_plural": "Contractor agreement documents",
            },
        ),
        migrations.AlterModelOptions(
            name="procurementdocuments",
            options={"ordering": ["display_order", "-uploaded_at"], "verbose_name_plural": "Procurement documents"},
        ),
        migrations.AddField(
            model_name="contractoragreementdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which choices are displayed on the landing page, from left to right, top to bottom. Lower values are displayed first.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="procurementdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which choices are displayed on the landing page, from left to right, top to bottom. Lower values are displayed first.",
            ),
            preserve_default=False,
        ),
    ]
