# Generated by Django 3.2.19 on 2023-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractoragreementdocuments_procurementdocuments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecontract',
            old_name='renewal_date',
            new_name='end',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='award_date',
            field=models.DateField(blank=True, help_text='The date this contract was awarded', null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='contract_number',
            field=models.CharField(blank=True, help_text='The contract number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The cost of this contract',
                                      max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='name',
            field=models.CharField(help_text='The name of the contract', max_length=255),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='requisition_number',
            field=models.CharField(blank=True, help_text='The requisition number for this contract', max_length=255,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='submitted_date',
            field=models.DateField(blank=True, help_text='The date this contract was submitted', null=True),
        ),
        migrations.AddField(
            model_name='contractoragreement',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='The reminder date for this contractor agreement', null=True),
        ),
        migrations.AddField(
            model_name='servicecontract',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='The reminder date for this service contract', null=True),
        ),
        migrations.AddField(
            model_name='servicecontract',
            name='start',
            field=models.DateField(blank=True, help_text='The start date of this service contract', null=True),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='end',
            field=models.DateField(blank=True, help_text='The end date of this service contract', null=True),
        ),
    ]
