# Generated by Django 4.2.11 on 2024-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_documents_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractoragreementdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which choices are displayed on the landing page, from left to right, top to bottom. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="procurementdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which choices are displayed on the landing page, from left to right, top to bottom. Lower values are displayed first.",
            ),
        ),
    ]
