# Generated by Django 4.2.15 on 2024-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_default_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractoragreementdocuments",
            name="name",
            field=models.CharField(
                blank=True, help_text="The optional name to display for this document", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractoragreementdocuments",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="procurementdocuments",
            name="name",
            field=models.CharField(
                blank=True, help_text="The optional name to display for this document", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="procurementdocuments",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
