# Generated by Django 3.2.13 on 2022-05-20 15:52

from django.db import migrations

import NEMO.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoralertemail',
            name='additional_email',
        ),
        migrations.AddField(
            model_name='sensoralertemail',
            name='additional_emails',
            field=NEMO.fields.MultiEmailField(blank=True, help_text='Additional email address to contact when this alert is triggered. A comma-separated list can be used.', max_length=2000, null=True),
        ),
    ]
