# Generated by Django 4.2.15 on 2024-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="data_label",
            field=models.CharField(blank=True, help_text="Label for graph and table data", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="data_prefix",
            field=models.CharField(blank=True, help_text="Prefix for sensor data values", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="data_suffix",
            field=models.CharField(blank=True, help_text="Suffix for sensor data values", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sensorcard",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sensorcard",
            name="server",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sensorcardcategory",
            name="name",
            field=models.CharField(help_text="The name for this sensor card category", max_length=255),
        ),
        migrations.AlterField(
            model_name="sensorcategory",
            name="name",
            field=models.CharField(help_text="The name for this sensor category", max_length=255),
        ),
    ]
