# Generated by Django 3.2.12 on 2022-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(),
        ),
    ]
