# Generated by Django 3.2.12 on 2022-04-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='data_label',
            field=models.CharField(blank=True, help_text='Label for graph and table data', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='visible',
            field=models.BooleanField(default=True, help_text='Specifies whether this sensor is visible in the sensor dashboard'),
        ),
        migrations.AddField(
            model_name='sensorcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sensors.sensorcategory'),
        ),
    ]
