# Generated by Django 4.2.16 on 2024-11-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_alter_sensor_options_sensor_last_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorcard",
            name="extra_args",
            field=models.TextField(
                blank=True,
                help_text="Json formatted extra arguments to pass to the sensor card implementation.",
                null=True,
            ),
        ),
    ]
