# Generated by Django 4.2.15 on 2024-11-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_alter_sensordata_created_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensor",
            options={"ordering": ["name"]},
        ),
    ]
