# Generated by Django 4.2.15 on 2024-10-13 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import NEMO.apps.credit_card_orders.pdf_utils
import NEMO.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "creation_time",
                    models.DateTimeField(auto_now_add=True, help_text="The date and time when the order was created."),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, help_text="The last time this order was modified."),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Approved"), (2, "Denied"), (3, "Fulfilled")], default=0
                    ),
                ),
                ("template_data", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cancelled", models.BooleanField(default=False, help_text="Indicates the order has been cancelled.")),
                ("cancellation_time", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_card_orders_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_card_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The last user who modified this order.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_card_orders_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardOrderDocumentType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The unique name for this item", max_length=255, unique=True)),
                (
                    "display_order",
                    models.IntegerField(
                        help_text="The display order is used to sort these items. The lowest value category is displayed first."
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditCardOrderPDFTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The unique name for this order template", max_length=255, unique=True),
                ),
                (
                    "form",
                    models.FileField(
                        help_text="The pdf form",
                        upload_to=NEMO.utilities.document_filename_upload,
                        validators=[NEMO.apps.credit_card_orders.pdf_utils.validate_is_pdf_form],
                    ),
                ),
                ("form_fields", models.TextField(help_text="JSON formatted fields list")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditCardOrderDocuments",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=NEMO.utilities.document_filename_upload,
                        verbose_name="Document",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The optional name to display for this document",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=1,
                        help_text="The order in which choices are displayed on the landing page, from left to right, top to bottom. Lower values are displayed first.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_card_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="credit_card_orders.creditcardorder"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credit_card_orders.creditcardorderdocumenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credit card order documents",
                "ordering": ["display_order", "-uploaded_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditCardOrderApprovalLevel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="The approval level number. Approval will be asked in ascending order"
                    ),
                ),
                (
                    "permission",
                    models.CharField(help_text="The role/permission required for users to approve", max_length=255),
                ),
                (
                    "can_edit_order",
                    models.BooleanField(
                        default=True, help_text="Check this box if the reviewer can make changes to the order"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="credit_card_orders.creditcardorderpdftemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["template", "level"],
                "unique_together": {("template", "level")},
            },
        ),
        migrations.AddField(
            model_name="creditcardorder",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="credit_card_orders.creditcardorderpdftemplate"
            ),
        ),
        migrations.CreateModel(
            name="CreditCardOrderSpecialMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "field_name",
                    models.CharField(help_text="The pdf template field name to map this value to", max_length=255),
                ),
                (
                    "field_value",
                    models.CharField(
                        choices=[
                            ("creator", "Order creator"),
                            ("creation_time", "Order creation time"),
                            ("number", "Order number"),
                            ("approved", "Order approved/denied"),
                            ("approved_by", "Order approved/denied by"),
                            ("approval_time", "Order approval time"),
                        ],
                        help_text="The special value to map it to",
                        max_length=255,
                    ),
                ),
                (
                    "field_value_boolean",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated values to map approved/denied states, i.e. 'Yes,No'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "field_value_approval",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approval level (for approval mappings only)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credit_card_orders.creditcardorderapprovallevel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="credit_card_orders.creditcardorderpdftemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["field_name"],
                "unique_together": {("template", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="CreditCardOrderApproval",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "approval_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date and time when the order was approved/denied."
                    ),
                ),
                ("approved", models.BooleanField(default=False, help_text="Whether this order was approved or not")),
                (
                    "approval_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credit_card_orders.creditcardorderapprovallevel",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        help_text="The user who approved the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_card_orders_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="credit_card_orders.creditcardorder"
                    ),
                ),
            ],
            options={
                "ordering": ["-approval_time"],
                "unique_together": {("order", "approval_level")},
            },
        ),
    ]
